server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: lb/cliente
          predicates:
            - Path= /clientes/**
          