server:
  port: 8089
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: http://localhost:8084/
          predicates:
            - Path=/cliente/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      #default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
    instance:
      #hostname: localhost
      instance-id: ${spring.application.name}:${sprin.application.instance_id:${random.value}}