server:
  port: 8090
spring:
  application:
    name: circuitbreaker
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
    instance:
      instance-id: ${spring.application.name}:${sprin.application.instance_id:${random.value}}
resilience4j.circuitbreaker:
    instances:
        clientCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate